# Generated by Django 2.1.5 on 2019-02-19 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='item.Buyer')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='in_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Cart'),
        ),
    ]
