# Generated by Django 2.1.5 on 2019-02-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20190219_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='in_cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Item'),
        ),
    ]
